# Copyright IBM Corp. All Rights Reserved.
# Modifications by karthik
#
# SPDX-License-Identifier: Apache-2.0
#
# Configuration file for the Cryto Generator tool
#

PeerOrgs:
  - Name: Hospital1
    Domain: hospital1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        CommonName: orderer0.hospital1.example.com
        SANS:
          - "localhost"
          - "172.18.0.242"
      - Hostname: peer0
        CommonName: peer0.hospital1.example.com
        SANS:
          - "localhost"
          - "172.18.0.242"
      - Hostname: peer1
        CommonName: peer1.hospital1.example.com
        SANS:
          - "localhost"
          - "172.18.0.115"

  - Name: Pharmacy1
    Domain: pharmacy1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        CommonName: orderer0.pharmacy1.example.com
        SANS:
          - "localhost"
          - "172.18.0.251"
      - Hostname: peer0
        CommonName: peer0.pharmacy1.example.com
        SANS:
          - "localhost"
          - "172.18.0.251"
      - Hostname: peer1
        CommonName: peer1.pharmacy1.example.com
        SANS:
          - "localhost"
          - "172.18.0.252"

  - Name: Practitioner1
    Domain: practitioner1.example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer0
        CommonName: orderer0.practitioner1.example.com
        SANS:
          - "localhost"
          - "172.18.0.97"
      - Hostname: peer0
        CommonName: peer0.practitioner1.example.com
        SANS:
          - "localhost"
          - "172.18.0.97"
      - Hostname: peer1
        CommonName: peer1.practitioner1.example.com
        SANS:
          - "localhost"
          - "172.18.0.138"
